wevesi/models/user.py
from flask import flash
from mongoengine import Document
from mongoengine.fields import StringField, EmailField, BooleanField, IntField

from wevesi import crypt

class User(Document):
    name = StringField(required=True)
    email = EmailField(required=True, unique=True)
    password = StringField(required=True)
    validated = BooleanField(default=False)
    user_type = StringField(default='user')
    active = BooleanField(default=True)
    login_attempts = IntField(default=0)


class UserObj(object):
    def __init__(self, user_obj=None):
        self._user_obj = user_obj


    @staticmethod
    def get(user_id):
        return User.objects(email=user_id).first()


    @staticmethod
    def login(user_id, password):
        valid = False
        user = None
        document = User.objects(email=user_id).first()
        if document:
            valid = crypt.check_password_hash(document['password'], password)
        if valid:
            user = UserObj(document)
            user.authenticated = True
        return user


    @staticmethod
    def create(name, user_id, password):
        user_created = False
        passwd_hash = crypt.generate_password_hash(password)
        try:
            User(name=name, email=user_id, password=passwd_hash).save()
        except Exception as e:
            flash(e.message, 'danger')
            user_created = False
        else:
            user_created = True
        return user_created


    def get_id(self):
        return getattr(self._user_obj, 'email', None)

    def is_authenticated(self):
        return getattr(self, 'authenticated', None)


    def is_active(self):
        return getattr(self._user_obj, 'active', None)


    def is_anonymous(self):
        return False

wevesi/forms/access.py
from flask_wtf import Form
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Email


class LoginForm(Form):
    email = StringField('Email', validators=[DataRequired(), Email()])
    passwd = PasswordField('Password', validators=[DataRequired()])


class SignupForm(Form):
    name = StringField('Name', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    passwd = PasswordField('Password', validators=[DataRequired()])
    passwd_verify = PasswordField('Verify Password',
                                  validators=[DataRequired()])

wevesi/__init__.py
# -*- coding: utf-8 -*-

from flask import Flask, render_template

from wevesi.crypt import crypt
from wevesi.db import db
from wevesi.blueprints.admin import admin
from wevesi.blueprints.base import base_listener, login_manager
from wevesi.blueprints.products import products_listener

app = Flask(__name__)
app.config.from_object('config')

# Jinja Prettiness
app.jinja_env.trim_blocks = True
app.jinja_env.lstrip_blocks = True

# Initialize extensions
admin.init_app(app)
crypt.init_app(app)
db.init_app(app)
login_manager.init_app(app)

# Initialize blueprints
app.register_blueprint(base_listener)
app.register_blueprint(products_listener, url_prefix='/products')


@app.add_template_filter
def category_or(string, default):
    category = default
    if string in ['success', 'info', 'warning', 'danger']:
        category = string
    return category


@app.errorhandler(401)
def forbidden_401(exception):
    return render_template('401.html'), 401


@app.errorhandler(403)
def forbidden_403(exception):
    return render_template('403.html'), 403


@app.errorhandler(404)
def forbidden_404(exception):
    return render_template('404.html'), 404

wevesi/blueprints/admin.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from flask_admin import Admin
from flask_admin.contrib.mongoengine import ModelView

from wevesi.models.user import User


class UserView(ModelView):
    pass

admin = Admin()
admin.add_view(UserView(User))

wevesi/blueprints/base.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import LoginManager, login_required, login_user, logout_user

from wevesi.forms.access import LoginForm, SignupForm
from wevesi.models.user import UserObj

base_listener = Blueprint('base_listener', __name__)
login_manager = LoginManager()


@login_manager.user_loader
def load_user(userid):
    """This loads a user"""
    return UserObj.get(userid)


@base_listener.route('/')
def index():
    return render_template('index.html')


@base_listener.route('/login', methods=['GET', 'POST'])
def login():
    form_login = LoginForm()
    if form_login.validate_on_submit():
        email = form_login.email.data
        passwd = form_login.password.data
        user = UserObj.login(email, passwd)
        if user:
            login_user(user)
            flash('Logged in successfully', 'success')
            return redirect(url_for('index'))
        else:
            flash('Unable to verify username and password', 'danger')
    return render_template('login.html', form=form_login)


@base_listener.route("/logout", methods=["GET"])
@login_required
def logout():
    """Logout the current user."""
    logout_user()
    flash('Disconected successfully', 'success')
    return redirect(url_for('index'))


@base_listener.route('/signup', methods=['GET', 'POST'])
def signup():
    form_signup = SignupForm()
    if form_signup.validate_on_submit():
        name = form_signup.name.data
        email = form_signup.email.data
        passwd = form_signup.password.data
        passwd_repeat = form_signup.password_repeat.data
        if passwd == passwd_repeat:
            user = UserObj.create(name, email, passwd)
            if user:
                flash('User created', 'success')
                return redirect(url_for('index'))
        else:
            flash('Passwords doesn\'t match', 'danger')
    return render_template('signup.html', form=form_signup)

wevesi/blueprints/products.py
from flask import Blueprint, render_template

products_listener = Blueprint('products', __name__)


@products_listener.route('/')
def list_products():
    return ''

wevesi/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="description" content="Webesi project">
		<meta name="author" content="paxet">
		<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}">
		<title>Wevesi {% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
		{% block head %}
		{% endblock %}
	</head>
	<body>
		<div class="container">
			<nav class="navbar navbar-inverse" role="navigation">
				<div class="container-fluid">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<a class="navbar-brand" href="#">Wevesi</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
						{% set userid = session.get('user_id') %}
						{% if userid %}
							<ul class="nav navbar-nav navbar-right">
								<li class="dropdown">
									<a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ userid|lower }} <b class="caret"></b></a></b>
									<ul class="dropdown-menu">
										<li><a href="{{ url_for('base_listener.logout') }}">Logout</a></li>
									</ul>
								</li>
							</ul>
						{% else %}
							<ul class="nav navbar-nav navbar-right">
								<li><a href="{{ url_for('base_listener.login') }}">Login</a></li>
							</ul>
						{% endif %}
					</div> <!-- navbar-collapse -->
				</div> <!-- container-fluid -->
			</nav>
			{% block container %}
				{% with messages = get_flashed_messages(with_categories=true) %}
					{% if messages %}
						<div id="messages">
							{% for category, message in messages %}
								<div class="alert alert-{{ category|category_or('info') }} alert-dismissable">
									<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
									<strong>{{ category|title }}:</strong> {{ message }}</strong>
								</div>
							{% endfor %}
						</div>
					{% endif %}
				{% endwith %}
			{% endblock %}
		</div>
		{% block body %}
		{% endblock %}

		<script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
		{% block script %}
		{% endblock %}
	</body>
</html>

wevesi/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block container %}
    {{ super() }}
    <div class="jumbotron">
        <h1>elemental</h1>
        <p class="lead">Base Application</p>
    </div>
{% endblock %}

wevesi/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block container %}
    {{ super() }}
    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <h1>Login</h1>
        </div>
        <br><br>
    </div>
    <div class="row">
        <form action="" method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-10">
                    <input type="email" class="form-control" name="email" id="inputEmail" placeholder="Email">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-10">
                    <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Sign In</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

wevesi/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block container %}
    {{ super() }}
    <div class="row">
        <div class="col-sm-offset-2 col-sm-10">
            <h1>Sign Up</h1>
        </div>
        <br><br>
    </div>
    <div class="row">
        <form action="" method="post" class="form-horizontal" role="form">
            {{ form.hidden_tag() }}
            {% for field in form %}
                {% if 'csrf' not in field.name %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field(class='form-control') }}
                            {% if field.errors %}
                                {% for error in field.errors %}
                                    <p class="text-danger"><strong>{{ error }}</strong></p>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}